Isn't backslash (`\`) escape too much?
previm/previm pull request #211
Opened 2024-11-21 02:24 UTC by KSR-Yasuda

In writing backslash (`/`), it is rendered as `//`.
Isn't it escaping too much?

Also, due to this, Mermaid graph using `/` may get syntax errors.

```text
flowchart LR

NodeSS[/" Node [/ /] "/]
NodeBB[\" Node [\\ \\] "\]
NodeSB[/" Node [/ \\] "\]
NodeBS[\" Node [\ /] "/]
Node["Node [\a] "]
```

* [LiveEditor](https://mermaid.live/edit#pako:eNplUM0KgzAMfpWSs9C7x7Ldth3W24yHYOsPaDu6ljHEd1_UKcgu4cv3k4SMUHljIYe69--qpRDF5Y4O3Y1prQuJIGYoCilkKRBkuWpKFYi7yBDFXGYL119eHfJ_utLHGccNBcIm0MyXkMFgw0Cd4XtHdILJ2NrBIuQMja0p9ZHnu4mt6Wko2rPpog-Qx5BsBpSi1x9Xbf3qOXXUBBogr6l_MWuXzHX9y_KeDIJPTbs7nuQe3m-J6QuTCGrr)

----

However, BTW, GitHub gets syntax errors for the Mermaid graph above.
Character escape is too complicated issue, huh?

```mermaid
flowchart LR

NodeSS[/" Node [/ /] "/]
NodeBB[\" Node [\\ \\] "\]
NodeSB[/" Node [/ \\] "\]
NodeBS[\" Node [\ /] "/]
Node["Node [\a] "]
```

2024-11-21 03:21 UTC, lambdalisue commented
Please check the test and fix it if the failure is expected.

2024-11-21 05:02 UTC, KSR-Yasuda commented
@lambdalisue

> Please check the test and fix it if the failure is expected.

Have no idea.
Isn't it from somewhere else?

The result says there's extra `\` before `.`.

```text
Run ./vim-themis/bin/themis test -r --reporter dot
...F........................

Failures:
  1) convert_to_content exists_double_quotes
     The equivalent values were expected, but it was not the case.
     
         expected: 'he said. \"Hello, john\"\nあいうえお漢字'
              got: 'he said\. \"Hello, john\"\nあいうえお漢字'

tests 28
passes 27
fails 1
Error: Process completed with exit code 1.
```

The test code gives no backslash (`\`) around the period (`.`).

[`test/autoload/previm_test`](https://github.com/previm/previm/blob/773c7c7090eb956284a729386272e51c808be3ec/test/autoload/previm_test.vim#L30)
```vim
 30 function! s:t.exists_double_quotes()
 31   let arg = ['he said. "Hello, john"', 'あいうえお漢字']
 32   let expected =
 33         \   'he said. \"Hello, john\"' . s:newline
 34         \ . 'あいうえお漢字'
 35   call s:assert.equals(previm#convert_to_content(arg), expected)
 36 endfunction
```

The fixed part is below.
No code looks related with string replacement of `\.`.

[`autoload/previm.vim`](https://github.com/previm/previm/blob/773c7c7090eb956284a729386272e51c808be3ec/autoload/previm.vim#L302)
```vim
302 function! previm#convert_to_content(lines) abort

      " (snip)

314   let converted_lines = []
315   for line in s:do_external_parse(a:lines)
316     " TODO エスケープの理由と順番の依存度が複雑

        " Change of this patch: '\\\\' → '\\'
317     let escaped = substitute(line, '\', '\\', 'g')

318     let escaped = previm#convert_relative_to_absolute_filepath(escaped, mkd_dir)
319     let escaped = substitute(escaped, '"', '\\"', 'g')
320     let escaped = substitute(escaped, '\r', '\\r', 'g')
321     call add(converted_lines, escaped)
322   endfor
323   return join(converted_lines, "\\n")
324 endfunction
```

2024-11-21 05:11 UTC, KSR-Yasuda commented
In the Actions tab, the same error had happened for `master` last week.
This is not a fault of this patch.

2024-11-28 04:00 UTC, lambdalisue requested changes
Could you add test for this?

2024-11-28 04:40 UTC, KSR-Yasuda commented
Did you rebase the branch?
You don't need this fix anymore, with 2a861ac5f1850e74cac1baccf85eabaec5dd4d43 reverted.

2024-11-28 04:43 UTC, closed without merging

2024-11-28 04:44 UTC, KSR-Yasuda commented
I'll close this PR.
If needed, we'd better discuss in #212 or such, since it is the degression of the commit.